// WARNING: DO NOT EDIT. This file is Auto-Generated by AWS Mobile Hub. It will be overwritten.

// Copyright 2017-2018 Amazon.com, Inc. or its affiliates (Amazon). All Rights Reserved.
// Code generated by AWS Mobile Hub. Amazon gives unlimited permission to
// copy, distribute and modify it.

// AWS Mobile Hub Project Constants
const awsmobile = {
    'aws_app_analytics': 'enable',
    'aws_cognito_identity_pool_id': 'us-east-1:b47e52da-49e3-4ec6-9eea-ecf8c53c2de1',
    'aws_cognito_region': 'us-east-1',
    'aws_content_delivery': 'enable',
    'aws_content_delivery_bucket': 'atlas-hosting-mobilehub-1208501123',
    'aws_content_delivery_bucket_region': 'us-east-1',
    'aws_content_delivery_cloudfront': 'enable',
    'aws_content_delivery_cloudfront_domain': 'dhxtkdo217ae3.cloudfront.net',
    'aws_mobile_analytics_app_id': '498cb0cac24b44409d88c4958bec94f4',
    'aws_mobile_analytics_app_region': 'us-east-1',
    'aws_project_id': 'd8349ef5-1ab5-11e8-b5df-89121fa705ee',
    'aws_project_name': 'atlas',
    'aws_project_region': 'us-east-1',
    'aws_resource_name_prefix': 'atlas-mobilehub-1208501123',
    'aws_sign_in_enabled': 'enable',
    'aws_user_pools': 'enable',
    'aws_user_pools_id': 'us-east-1_rl1irryXP',
    'aws_user_pools_mfa_type': 'ON',
    'aws_user_pools_web_client_id': '4i3s2scd8dt3jm8pih4ngbqesa',
}

export default awsmobile;
